# global config
# just log file for now
# maybe an ssh key could go in here
log_file: "./zfsbackup.log"
lock_file: "./zfsbackup.lock"
retain_snaps: 4
# dataset config
datasets:
  -
    dataset_name: "store/testing/test_set"
    destinations: 
    -
      dest: "store/backup/test_set"
      transport: "local"
      retain_snaps: 5
  -
    dataset_name: "store/testing/test_set2"
    destinations:
    -
      dest: "store/backup/test_set2"
      transport: "ssh:root@somehostname.whatever"
